# Generated by Django 4.1 on 2022-09-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofiles',
            managers=[
            ],
        ),
    ]
