# Generated by Django 4.1 on 2022-10-05 03:35

from django.db import migrations, models
import products.models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofiles_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name=profiles.models.userprofiles)),
                ('product_id', models.BigIntegerField(verbose_name=products.models.products)),
            ],
        ),
    ]
