# Generated by Django 4.1 on 2022-10-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
