# Generated by Django 4.1 on 2022-10-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_cart_product_id_alter_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='ref_id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
