# Generated by Django 4.1 on 2022-10-24 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userprofiles_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='walletTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(default=0)),
                ('CrDr', models.CharField(choices=[('Cr', 'Cr'), ('dr', 'dr')], max_length=20)),
                ('desc', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
