# Generated by Django 4.1 on 2022-10-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_wallettrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettrans',
            name='CrDr',
            field=models.CharField(choices=[('Credited', 'Credited'), ('Debited', 'Debited')], max_length=20),
        ),
    ]
