# Generated by Django 4.1 on 2022-10-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_wallettrans_crdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
