# Generated by Django 4.1 on 2022-10-29 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_code', models.CharField(max_length=100, unique=True)),
                ('minimum', models.FloatField(default=0)),
                ('maxlimit', models.FloatField(default=0)),
                ('discount_rate', models.FloatField(default=0)),
                ('discount_type', models.CharField(choices=[('FLAT', 'FLAT'), ('UPTO', 'UPTO')], default='FLAT', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True)),
                ('quantity', models.IntegerField()),
                ('Total', models.FloatField()),
                ('payment', models.CharField(default='COD', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('payment_id', models.CharField(max_length=500, null=True)),
                ('Offer_applied', models.TextField(null=True)),
                ('coupon_applied', models.TextField(null=True)),
                ('discount_price', models.FloatField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
