# Generated by Django 4.1.2 on 2022-11-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
