# Generated by Django 4.1 on 2022-10-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_code', models.CharField(max_length=100)),
                ('minimum', models.FloatField(default=False)),
                ('discount_rate', models.FloatField()),
                ('discount_type', models.CharField(choices=[('FLAT', 'FLAT'), ('UPTO', 'UPTO')], default='FLAT', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='Offer_applied',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='discount_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Coupon_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.coupons'),
        ),
    ]
