# Generated by Django 4.1 on 2022-10-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupons_orders_offer_applied_orders_discount_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Coupon_applied',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.coupons'),
        ),
    ]
