# Generated by Django 4.1 on 2022-10-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Coupon_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.coupons'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Offer_applied',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
