# Generated by Django 4.1 on 2022-10-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categories_maxlimit_categories_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Dis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='Disrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='Offer',
            field=models.BooleanField(null=True),
        ),
    ]
