# Generated by Django 4.1 on 2022-10-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_dis_products_disrate_products_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Offer',
            field=models.BooleanField(default=False),
        ),
    ]
