# Generated by Django 4.1.2 on 2022-11-05 04:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sub_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
